### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by marillat** [chaudum/rgain#4]
I try to use your rgain version under Debian unstable amd64 Python 3.7
but I've this error

```
/usr/lib/python3.7/dist-packages/rgain/script/__init__.py:24: PyGIWarning: Gst was imported without specifying a version first. Use gi.require_version('Gst', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gst  # noqa
Traceback (most recent call last):
  File "/usr/bin/collectiongain", line 7, in <module>
    collectiongain()
  File "/usr/lib/python3.7/dist-packages/rgain/script/collectiongain.py", line 353, in collectiongain
    opts.mp3_format, opts.ignore_cache, opts.jobs)
  File "/usr/lib/python3.7/dist-packages/rgain/script/collectiongain.py", line 267, in do_collectiongain
    music_dir = un(music_dir, getfilesystemencoding())
  File "/usr/lib/python3.7/dist-packages/rgain/script/__init__.py", line 57, in un
    return arg.decode(encoding)
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by chaudum** [comment]
Hi @marillat 
Thanks for reporting. Seems like there are still some Python 2 leftovers in the scripts module. I will have a look asap.

**Comment by chaudum** [comment]
I've merged a [fix](https://github.com/chaudum/rgain/pull/5) into master. Would you mind testing again?
Btw, may I ask, are you maintainer of the Debian multimedia packages? @marillat

**Comment by marillat** [comment]
@chaudum No I'm not a member of the multimedia Team. I'm the maintainer of https://www.deb-multimedia.org/
The best is to try the latest git master or simply this fix ?

**Comment by chaudum** [comment]
> The best is to try the latest git master or simply this fix ?

You can test `master`.

**Comment by marillat** [comment]
Seems to work for me.

Tested with 17 ogg files, 18 mp3 files and 19 flac files.
id3 tags displayed by eyeD3
output from file tagged by both version (python2 and python3) are the same.

I see only this warning with the python3 version.
```
/usr/lib/python3/dist-packages/rgain/script/__init__.py:24: PyGIWarning: Gst was imported without specifying a version first. Use gi.require_version('Gst', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gst  # noqa```

**Comment by chaudum** [comment]
The warnings will be removed with the following PR: https://github.com/chaudum/rgain/pull/9

**Comment by marillat** [comment]
Do you think the code is ready for a new release ?

**Comment by chaudum** [comment]
I've found a bug whilst running rgain on a file that did not contain an ID3 header
There is a PR for the fix, but yet untested. https://github.com/chaudum/rgain/pull/7/files
Is this a blocker for a release?

Regarding release: To be honest, I have no idea how this was previously done. Do you have a CD pipeline for packaging? If you want, we could arrange a call, just drop me an email christian.haudum@gmail.com

**Comment by marillat** [comment]
> I've found a bug whilst running rgain on a file that did not contain an ID3 header
> There is a PR for the fix, but yet untested. https://github.com/chaudum/rgain/pull/7/files
> Is this a blocker for a release?

The code must contains no know bug.

>A CD pipeline for packaging ?

What do you mean ?

**Comment by chaudum** [comment]
> > I've found a bug whilst running rgain on a file that did not contain an ID3 header
> > There is a PR for the fix, but yet untested. https://github.com/chaudum/rgain/pull/7/files
> > Is this a blocker for a release?
> 
> The code must contains no know bug.

Alright. I will get the fix tested and merged first :)

> 
> > A CD pipeline for packaging ?
> 
> What do you mean ?

How do you build the distribution package? Do you need a source distribution of the Python package, or a wheel? Do you build from source? Is there a build tooling for the package in place?
Sorry, I don't know yet how Python packages find their way into a Debian package repo :)

**Comment by marillat** [comment]
Debian packages are build from source so a simple new release is enough.
We have a tracker able to scan a repository for a new version
https://tracker.debian.org/pkg/rgain
but as this tracker is set to the python2 code I'll file a bug report to tell the actual Debian maintainer that the code is here and a new version is available for python 3.

**Comment by chaudum** [comment]
Hey @marillat 
Sorry for the delay. I have another question ;) Since the original author Felix Krull is not responding to any enquires regarding taking over code ownership I consider renaming this package of the Python 3 port `rgain3` and start with version `1.0.0`. Do you have any objections?

**Comment by chaudum** [comment]
Btw, the one known bug is fixed (https://github.com/chaudum/rgain/pull/7)

**Comment by marillat** [comment]
No objection.

**Comment by chaudum** [comment]
Here we go: https://github.com/chaudum/rgain/commit/793ffc501d3002328e6711d3b6a3adcaa191a8fd
